<?php
/*
Copyright (c) 2005, Alex Tingle.  $Revision: 287 $

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

/** Represents all posts from a particular day.
 *  Generated by ec3_util_calendar_days(). */
class ec3_Day
{
  var $is_event =False;
  var $titles   =array();
  function ec3_Day(){}
  function add_post($title,$time,$is_event)
  {
    $safe_title=strip_tags($title);
    $safe_title=
      str_replace(
        array(',','@'),
        ' ',
        htmlspecialchars(
          stripslashes($safe_title),
          ENT_QUOTES,
          get_option('blog_charset')
        )
      );
    if($is_event)
    {
      $safe_title.=' @'.$time;
      $this->is_event=True;
    }
    $this->titles[]=$safe_title;
  }
  function get_titles()
  {
    return implode(', ',$this->titles);
  }
}

?>
